church_name: Academy Street Baptist Church
church_logo_image_path: /uploads/academystreetlogo2.png
church_logo2_image_path: /uploads/academystreetlogo2.png
main_image: /uploads/background.jpg
phone: (336) 495-1205
church_email: greenanthony972@yahoo.com
facebook: 'https://www.facebook.com/Academy-Street-Baptist-Church-Randleman-1285949618104347'
twitter:
youtube:
address: 326 W Academy Street
address2:
City: Randleman
State: NC
Zip: '27317'
lattitude: '35.8180272'
longitude: '-79.8124606'
map_zoom_level: 14
main_blog_image: /uploads/1.jpg
main_sermon_image: /uploads/2.jpg
default_calendar_image: /uploads/hartwell.jpg
Google_calendar_id: leonhart4@gmail.com